### ISSUE TITLE
Can I run docs offline ?

### ISSUE THREAD

**Issue by Mu9tafa-Online** [directus/docs-v7#21]
Can I run docs offline: is there any setup should I follow ?

**Comment by benhaynes** [comment]
Hey @Mu9tafa-Online – I'm no expert, but you should be able to:

1. Clone the repo locally
1. cd to the Docs root
1. `npm install`
1. `npm run dev`

That's what I do and it works great! I'll add this to the README to help others...

**Comment by benhaynes** [comment]
Actually I can't add it to the README since that is the homepage of our Docs ;)

I'll add it to the.... Docs!
